# Generated by Django 4.1.6 on 2024-06-07 10:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_alter_search_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
